AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 bucket, SQS queue, and EC2 instance without key pair

Parameters:
  UniqueSuffix:
    Type: String
    Description: Unique suffix for resource names

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "utkarsh-bucket-${UniqueSuffix}"

  MySQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "utkarsh-queue-${UniqueSuffix}"

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c618421e203fe3f2  # Amazon Linux 2 (Mumbai region)
      Tags:
        - Key: Name
          Value: !Sub "Utkarsh-Instance-${UniqueSuffix}"
